apiVersion: v1
kind: ConfigMap
metadata:
  name: nlp-api-cfg
data:
  tock_mongo_url: mongodb://mongo1-svc:27017,mongo2-svc:27017,mongo3-svc:27017/?replicaSet=tock
  nlp_duckling_url: htttp://duckling-svc:8080
  tock_env: prod
  tock_web_use_default_cors_handler: "true"
  tock_web_use_default_cors_handler_with_credentials: "false"
  tock_web_use_default_cors_handler_url: "*"
