apiVersion: v1
kind: Service
metadata:
  name: nlp-api-svc
spec:
  #type: NodePort
  ports:
    - protocol: TCP
      port: 8080
  selector:
    type: tock-studio
    service: nlp-api

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nlp-api
spec:
  replicas: 1
  selector:
    matchLabels:
      type: tock-studio
      service: nlp-api
  template:
    metadata:
      labels:
        type: tock-studio
        service: nlp-api
    spec:
      containers:
        - name: nlp-api
          image: tock/nlp_admin:latest
          livenessProbe:
            httpGet:
              path: /rest/admin/healthcheck
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 1 # Defaults to 1
            periodSeconds: 10 # Defaults to 10
            failureThreshold: 3 # Defaults to 3
          envFrom:
            - configMapRef:
                name: nlp-api-cfg