# See https://kind.sigs.k8s.io/docs/user/ingress/
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  # add a mount from /path/to/my/files on the host to /files on the node
  extraMounts:
  - hostPath: tock-mongo-data/mongo-0
    containerPath: /tmp/tock-mongo/mongo-0
  - hostPath: tock-mongo-data/mongo-1
    containerPath: /tmp/tock-mongo/mongo-1
  - hostPath: tock-mongo-data/mongo-2
    containerPath: /tmp/tock-mongo/mongo-2
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
        authorization-mode: "AlwaysAllow"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP