kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mongodb-sc
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-mongo-0
spec:
  capacity:
    storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mongodb-sc
  local:
    path: /tmp/tock-mongo/mongo-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: tock.ai/type
              operator: In
              values:
                - tock
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-mongo-1
spec:
  capacity:
    storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mongodb-sc
  local:
    path: /tmp/tock-mongo/mongo-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: tock.ai/type
              operator: In
              values:
                - tock
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-mongo-2
spec:
  capacity:
    storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mongodb-sc
  local:
    path: /tmp/tock-mongo/mongo-2
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: tock.ai/type
              operator: In
              values:
                - tock
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-pvc-mongo-0
spec:
  storageClassName: mongodb-sc
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-pvc-mongo-1
spec:
  storageClassName: mongodb-sc
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-pvc-mongo-2
spec:
  storageClassName: mongodb-sc
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi