apiVersion: v1
kind: Service
metadata:
  name: build-worker-svc
spec:
  #type: NodePort
  ports:
  - protocol: TCP
    port: 8080
  selector:
    type: tock-studio
    service: build-worker

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: build-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      type: tock-studio
      service: build-worker
  template:
    metadata:
      labels:
        type: tock-studio
        service: build-worker
    spec:
      containers:
      - name: build-worker
        image: tock/build_worker:latest
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 1 # Defaults to 1
          periodSeconds: 10 # Defaults to 10
          failureThreshold: 3 # Defaults to 3
        envFrom:
        - configMapRef:
            name: build-worker-cfg