apiVersion: v1
kind: ConfigMap
metadata:
  name: bot-api-cfg
data:
  tock_mongo_url: mongodb://mongo-0.mongo:27017,mongo-1.mongo:27017,mongo-2.mongo:27017/?replicaSet=tock
  tock_nlp_service_url: http://nlp-api-svc:8080
  tock_env: integ
  tock_websocket_enabled: "true"
  tock_web_sse: "true"
  tock_web_use_default_cors_handler: "false"
  tock_web_use_default_cors_handler_with_credentials: "false"
  tock_web_use_default_cors_handler_url: "*"

