apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-cm
  labels:
    project: tock
data:
  mongo.conf: |
    storage:
      dbPath: /data/db
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-setup-cm
  labels:
    project: tock
data:
  setup.sh: |
    #!/bin/bash

    echo "Waiting for startup.."
    until mongo --host mongo1-svc:27017 --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)' &>/dev/null; do
      printf '.'
      sleep 1
    done
    until mongo --host mongo2-svc:27017 --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)' &>/dev/null; do
      printf '.'
      sleep 1
    done
    until mongo --host mongo3-svc:27017 --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)' &>/dev/null; do
      printf '.'
      sleep 1
    done

    echo "Started.."

    echo setup.sh time now: `date +"%T" `
    mongo --host mongo1-svc:27017 <<EOF
       var cfg = {
            "_id": "tock",
            "members": [
                {
                    "_id": 0,
                    "host": "mongo1-svc:27017"
                },
                {
                    "_id": 1,
                    "host": "mongo2-svc:27017"
                },
                {
                    "_id": 2,
                    "host": "mongo3-svc:27017"
                }
            ]
        };
        rs.initiate(cfg, { force: true });
        rs.reconfig(cfg, { force: true });
    EOF