apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app: mongo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: mongo
  replicas: 3
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        type: mongo
        app: mongo
        selector: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:3.6.5
          volumeMounts:
            - name: mongodb-conf
              mountPath: /config
              readOnly: true
            - name: mongo-pvc
              mountPath: /data/db
          command: ["mongod"]
          args: ["--smallfiles", "--bind_ip_all", "--port", "27017", "--replSet", "tock"]
      volumes:
        - name: mongodb-conf
          configMap:
            name: mongodb-cm
            items:
              - key: mongo.conf
                path: mongo.conf
  volumeClaimTemplates:
    - metadata:
        name: mongo-pvc
      spec:
        storageClassName: mongodb-sc
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 50Mi