apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-setup
  labels:
    project: tock
spec:
  template:
    spec:
      containers:
      - name: mongo-setup
        image: mongo:3.6.5
        volumeMounts:
          - name: mongodb-setup
            mountPath: /scripts
            readOnly: false
        command: ["/scripts/setup.sh"]
      restartPolicy: Never
      volumes:
        - name: mongodb-setup
          configMap:
            name: mongodb-setup-cm
            defaultMode: 0777
            items:
              - key: setup.sh
                path: setup.sh