apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: tock-studio
spec:
  rules:
    - host: tock-studio
      http:
        paths:
          - path: /
            backend:
              serviceName: bot-admin-svc
              servicePort: 8080
