apiVersion: v1
kind: ConfigMap
metadata:
  name: bot-admin-cfg
data:
  tock_mongo_url: mongodb://mongo-0.mongo:27017,mongo-1.mongo:27017,mongo-2.mongo:27017/?replicaSet=tock
  nlp_duckling_url: http://duckling-svc:8080
  tock_env: prod
  tock_bot_admin_rest_default_base_url: http://bot-api-svc:8080
  tock_bot_compiler_service_url: http://kotlin-compiler-svc:8080
  tock_configuration_bot_default_base_url: http://bot-api-svc:8080
  tock_bot_api: "true"
  tock_https_env: "false"
  adminverticle_body_limit: "-1"