apiVersion: v1
kind: ConfigMap
metadata:
  name: bot-admin-cfg
data:
  tock_mongo_url: mongodb://mongo1-svc:27017,mongo2-svc:27017,mongo3-svc:27017/?replicaSet=tock
  nlp_duckling_url: http://duckling-svc:8080
  tock_env: prod
  tock_bot_admin_rest_default_base_url: http://tock-studio
  tock_bot_compiler_service_url: http://kotlin_compiler:8080
  tock_configuration_bot_default_base_url: http://tock-studio
  tock_https_env: "false"
  adminverticle_body_limit: "-1"