apiVersion: v1
kind: Service
metadata:
  name: bot-admin-svc
spec:
  #type: NodePort
  ports:
    - protocol: TCP
      port: 8080
  selector:
    type: tock-studio
    service: bot-admin

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      type: tock-studio
      service: bot-admin
  template:
    metadata:
      labels:
        type: tock-studio
        service: bot-admin
    spec:
      containers:
        - name: bot-admin
          image: tock/bot_admin:latest
          livenessProbe:
            httpGet:
              path: /rest/admin/healthcheck
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 1 # Defaults to 1
            periodSeconds: 10 # Defaults to 10
            failureThreshold: 3 # Defaults to 3
          envFrom:
            - configMapRef:
                name: bot-admin-cfg